FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN apt-get update && apt-get install -y git

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

RUN python -m nltk.downloader \
    stopwords \
    punkt \
    punkt_tab \
    wordnet \
    omw-1.4

COPY . .

RUN chmod +x start-render.sh

ENV API_URL=http://127.0.0.1:8000

EXPOSE 8501

CMD ["bash", "start-render.sh"]